DROP DATABASE IF EXISTS whiTee;
CREATE DATABASE whiTee;
USE whiTee;

DROP TABLE IF EXISTS Maglietta;

CREATE TABLE Maglietta (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    prezzo FLOAT DEFAULT 0 NOT NULL,
    IVA INT DEFAULT 0 NOT NULL,
    colore VARCHAR(30) NOT NULL,
    tipo VARCHAR(30) NOT NULL
);